version: 1.0
name: node_exporter_arm64

variables:
  DOCKERFILE_PATH: Dockerfile.arm
  DOCKER_IMAGE_NAMESPACE: cos
  DOCKER_IMAGE_REPO: node_exporter
  ARCH: 'arm64'
  VERSION: v0.18.0

privatecloud:
  version: v3

git:
  depth: 1

# machine表示编译机配置，standard表示基于VM编译
machine:
  standard:
    arm64_docker18:
      - default

# scripts中定义构建命令行，通过定义的构建命令行可以构建出artifacts中定义的构建产物
# 在scripts中可直接使用系统环境变量
# {{FW_REPO_VERSION}} 表示git commit信息
scripts:
  - sudo docker build --pull -t reg.docker.alibaba-inc.com/{{DOCKER_IMAGE_NAMESPACE}}/{{DOCKER_IMAGE_REPO}}-{{ARCH}}:{{VERSION}}-{{FW_REPO_VERSION}} -f {{DOCKERFILE_PATH}} .
  - sudo docker push reg.docker.alibaba-inc.com/{{DOCKER_IMAGE_NAMESPACE}}/{{DOCKER_IMAGE_REPO}}-{{ARCH}}:{{VERSION}}-{{FW_REPO_VERSION}}

artifacts:
  images:
    - reg.docker.alibaba-inc.com/{{DOCKER_IMAGE_NAMESPACE}}/{{DOCKER_IMAGE_REPO}}-{{ARCH}}:{{VERSION}}-{{FW_REPO_VERSION}} | {{DOCKERFILE_PATH}}

# notifications定义通知人员列表，目前只支持邮件通知
notifications:
  email:
    - zhongwei.lzw@alibaba-inc.com