FROM reg.docker.alibaba-inc.com/cos/golang:1.12.9-arm64 AS build-env
ADD . /go/src/prometheus/node_exporter 
WORKDIR /go/src/prometheus/node_exporter 
RUN make build

FROM busybox:e85c279b86c6dc690629fdec20c93fbb86a95e3d0e94c6e957517797f7bce08e
LABEL maintainer="The Prometheus Authors <prometheus-developers@googlegroups.com>"

COPY --from=build-env /go/src/prometheus/node_exporter/.build/arm64-linux/node_exporter /bin/node_exporter

EXPOSE      9100
USER        nobody
ENTRYPOINT  [ "/bin/node_exporter" ]
