FROM reg.docker.alibaba-inc.com/cos/golang:1.12.9-arm64 AS build-env
ADD . /go/src/prometheus/node_exporter 
WORKDIR /go/src/prometheus/node_exporter 
RUN make

FROM reg.docker.alibaba-inc.com/cos/busybox-glibc-arm64:latest
LABEL maintainer="The Prometheus Authors <prometheus-developers@googlegroups.com>"

COPY --from=build-env /go/src/prometheus/node_exporter/.build/arm64-linux/node_exporter /bin/node_exporter

EXPOSE      9100
USER        nobody
ENTRYPOINT  [ "/bin/node_exporter" ]
